name: Export starter and migration templates

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  export-packages:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Package templates
        run: |
          mkdir -p build/packages
          zip -r build/packages/starter.zip . \
            -x '.git/*' 'build/*' '.github/scripts/update_version' \
            '.github/workflows/buildscript-maintenance.yml' \
            '.github/workflows/release-packages.yml' \
            '*docs/*' 'README.md' 'LICENSE' 'gtnhShared/*'
          zip -r build/packages/migration.zip . \
            -x '.git/*' 'build/*' '.github/scripts/update_version' \
            '.github/workflows/buildscript-maintenance.yml' \
            '.github/workflows/release-packages.yml' \
            '*docs/*' 'src/*' 'README.md' 'LICENSE' 'gtnhShared/*'
      - uses: actions/upload-artifact@v7
        with:
          name: starter-and-migration-templates
          path: build/packages/*.zip
          if-no-files-found: error
